### ISSUE TITLE
Glasstron does not seem to work

### ISSUE THREAD

**Issue by busybox11** [katacarbix/android-messages#3]
I'm running your app on my Debian 10 (Linux) with compton compositor and blur, but Glasstron does not seem to work.
I tried enabling transparency in the developer tools but I only get a white background.
Do we need to pack our own Glasstron ASAR file and edit the `package.json` file , just like for the other electron apps ?

**Comment by katacarbix** [comment]
You ran `npm install`, correct? It should get Glasstron automatically.

Try making your changes to the style and then running `ElectronApi.require('electron').remote.getCurrentWindow().setBackgroundColor('transparent')` in the console and let me know how that goes.

**Comment by busybox11** [comment]
Actually, I'm running `npm start`. I'm going to try with `npm install` obviously, but it should be the same thing ?
(I'm a novice in electron, it's probably not lol)

**Comment by katacarbix** [comment]
They're two different commands. You should always install before starting.

**Comment by busybox11** [comment]
Oh, yeah, I see.
I ran `npm install` before, obviously. I misunderstood what you said.
I ran `npm start` after.
I'm going to edit the file RN

**Comment by busybox11** [comment]
Aaaaaand it's not working either.

**Comment by katacarbix** [comment]
Then try my suggestion in the first comment.

**Comment by busybox11** [comment]
I did it, that's what I said.
(My english isn't the best too, I'm from France...)

**Comment by katacarbix** [comment]
That's okay. I suspect this is an individual issue, so let's move this to Discord DMs.

**Comment by busybox11** [comment]
Okay.

**Comment by katacarbix** [comment]
Issue resolved in private messages.
